services:
  cv-project:
    build: .
    container_name: cv-project
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - .:/app
    stdin_open: true
    tty: true
